### PR TITLE
Replace all env vars in process types before writing docker-compose.yml

### PR DESCRIPTION
**Pull request by jkutner**
This doesn't cover all cases. But my javascript is weak. We need to replace things like `${PORT:-"8080"}`.  regex?

### CODE REVIEW

**Comment by jkutner** [comment]
Here's a sample app: https://github.com/kissaten/play-2.4.x-scala/tree/docker

**Comment by jkutner** [comment]
This is a worse problem i think. I tried setting up JRuby, and the Procfile looks like this:

```
web: bundle exec puma -p $PORT -e ${RACK_ENV:-development} -t ${PUMA_MIN_THREADS:-5}:${PUMA_MAX_THREADS:-5}
```

Here's the app: https://github.com/kissaten/jruby-minimal/tree/docker

When i run with `docker-compose` it appears the env vars are never evaluated at all:

```sh-session
$ docker-compose up web
Recreating jrubyminimal_herokuPostgresql_1...
Recreating jrubyminimal_web_1...
Attaching to jrubyminimal_web_1
web_1 | uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
web_1 | The signal USR1 is in use by the JVM and will not work correctly on this platform
web_1 | Puma starting in single mode...
web_1 | * Version 2.11.2 (jruby 2.2.2), codename: Intrepid Squirrel
web_1 | * Min threads: ${PUMA_MIN_THREADS, max threads: -5}
web_1 | * Environment: ${RACK_ENV:-development}
web_1 | * Listening on tcp://0.0.0.0:8080
web_1 | Use Ctrl-C to stop
web_1 | ArgumentError: invalid value for Integer: "${PUMA_MIN_THREADS"
web_1 |      Integer at org/jruby/RubyKernel.java:428
web_1 |   initialize at /app/.jruby/lib/ruby/gems/shared/gems/puma-2.11.2-java/lib/puma/thread_pool.rb:24
web_1 |          run at /app/.jruby/lib/ruby/gems/shared/gems/puma-2.11.2-java/lib/puma/server.rb:241
web_1 |          run at /app/.jruby/lib/ruby/gems/shared/gems/puma-2.11.2-java/lib/puma/single.rb:96
web_1 |          run at /app/.jruby/lib/ruby/gems/shared/gems/puma-2.11.2-java/lib/puma/cli.rb:216
web_1 |        <top> at /app/.jruby/lib/ruby/gems/shared/gems/puma-2.11.2-java/bin/puma:10
web_1 |         load at org/jruby/RubyKernel.java:958
web_1 |        <top> at /app/.jruby/bin/puma:23
jrubyminimal_web_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
```

I still think we can handle this in the `init.js`, but I'm not sure how.

**Comment by jkutner** [comment]
Thinking about this some more... it just doesn't make sense. Why would the $PORT or $RAILS_ENV not eval? 

It's like docker-compose is escaping the env vars.

**Comment by hunterloftis** [comment]
What if we wrap the command in something like `bash -c` ?

```
web: bash -c "${ actual_commands }"
```

**Comment by jkutner** [comment]
@hunterloftis just tried that. Somehow, it works for jruby, but not scala. I'm removing all my caches to try and figure it out.

It makes the docker-compose.yml a little ugly, but I'm starting to wonder if that should be regenerated on the fly anyways (treat it as compiled code).

**Comment by hunterloftis** [comment]
@jkutner the tricky part with compiling docker-compose.yml on-the-fly is that the in-the-middle commands (docker-compose foobar) don't run through heroku-docker... so there's no place to hook in a compile step.

**Comment by jkutner** [comment]
@hunterloftis it was the [init script](https://github.com/jkutner/scala-image/blob/master/init) that was breaking Scala.

I'm fine with `bash -c` then. I'll update the PR accordingly.

**Comment by hunterloftis** [comment]
@jkutner after that last commit, does everything work for you in jvm-land?

**Comment by jkutner** [comment]
@hunterloftis my last commit? if so, then yes: wrapping the procfile command in `bash -c '...'` fixes everything so long as the quotes are escaped.

**Pull request merged**
