### PR TITLE
test and implementation for consistent newlines

### PR DESCRIPTION
**Pull request by hunterloftis**

### CODE REVIEW

**Comment by friism** [comment]
Thanks, looks good :-).

I think @freeformz griped that `app.json` was written to the filesystem even though no changes were made to it. I don't think it's a big problem though.

**Comment by freeformz** [comment]
@friism it's just annoying and inconvenient. I'd rather it not touch the file if it doesn't need to.

**Comment by hunterloftis** [comment]
@freeformz if the pre/post files are identical, why would it be annoying or inconvenient?

**Comment by freeformz** [comment]
If they change my git status then it's annoying.

**Pull request merged**
