### PR TITLE
test and implementation for :init, --force, and --image

### PR DESCRIPTION
**Pull request by hunterloftis**
- Tests! This adds some basic tests for `:init`. I don't love using fixtures in tests, except for a few sweeping integration tests, but this is a simple way to start with tests in the project.
- `:init` accepts an `--image` flag
- `:init` creates app.json if the file is missing and an `--image` is specified
- `:init` no longer blows away Dockerfile and docker-compose.yml if they exist
- `:init` accepts a `--force` flag that *will* blow existing files away

/cc @friism @freeformz

### CODE REVIEW

**Comment by hunterloftis** [comment]
Should also resolve https://github.com/heroku/heroku-docker/pull/117

**Comment by matthew-andrews** [comment]
Seems good, thanks!!

**Comment by matthew-andrews** [comment]
i don't think you meant to commit the `.DS_Store` files thoguh

**Comment by hunterloftis** [comment]
https://github.com/heroku/heroku-docker/commit/66472d933653465b6d3467a7721d2149c43e7d88

Thanks! :+1:

**Comment by friism** [comment]
Awesome, thanks @hunterloftis

**Pull request merged**
